### ISSUE TITLE
Submit as Activator template?

### ISSUE THREAD

**Issue by lucperkins** [jacobus/s4#3]
I built something similar a while back (repo is [here](https://github.com/lucperkins/spray-akka-slick-postgres)), but this is _far_ better. I would suggest submitting yours as a Typesafe [Activator template](https://github.com/lucperkins/spray-akka-slick-postgres). Info on that is [here](http://typesafe.com/activator/template/contribute). Great stuff! I've learned a lot from it already.

**Comment by jacobus** [comment]
Closing this Activator templates went the way of the dodo in 2017

**Comment by lucperkins** [comment]
Oh boy, this was a blast from the past 😂
